stages:
  - deploy

variables:
  NETWORK_NAME: br0
  DOMAIN: quecarta.com
  IMAGE_NAME: $DOMAIN/website:latest
  CONTAINER_IP: 172.18.0.122
  CONTAINER_NAME: quecarta-website

deploy-sandbox:
  stage: deploy
  only:
    - develop
  tags:
    - apps
    - sandbox
  variables:
    DOMAIN: sandbox.quecarta.com
  before_script:
    - docker build --build-arg="DOMAIN=$DOMAIN" --cache-from="$IMAGE_NAME" -t $IMAGE_NAME .
  script:
    - docker rm -f $CONTAINER_NAME || true
    - docker run
      --restart="always"
      --network="$NETWORK_NAME"
      --ip="$CONTAINER_IP"
      --log-opt="max-size=20M"
      --log-opt="max-file=5"
      --name="$CONTAINER_NAME"
      -e="DOMAIN=$DOMAIN"
      -d $IMAGE_NAME
